# Copyright Contributors to the Pyro project.
#
# SPDX-License-Identifier: Apache-2.0

[tool.ruff]
extend-exclude = ["*.ipynb"]
line-length = 120


[tool.ruff.lint]
ignore = ["E741", "E721"]
select = ["E", "F", "I"]
