name: CI

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

env:
  CXX: g++-8
  CC: gcc-8
  COVERALLS_PARALLEL: true
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nbstripout nbformat
    - name: Lint with flake8
      run: |
        make lint
  docs:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          # Keep track of pyro-api master branch
          pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip
          pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install .[test]
          sudo apt-get install graphviz
          pip install -r docs/requirements.txt
          pip freeze
      - name: Build docs and run doctest
        run: |
          make docs
          make doctest
  unit:
    runs-on: ubuntu-latest
    needs: docs
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          # Keep track of pyro-api master branch
          pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip
          pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          sudo apt-get install ninja-build
          pip install .[test]
          pip install coveralls
          pip freeze
      - name: Run unit tests
        run: |
          pytest -vs --cov=pyro --cov-config .coveragerc --stage unit --durations 20
      - name: Submit to coveralls
        run: GITHUB_SHA="$GITHUB_RUN_ID" GITHUB_REF="" coveralls
  examples:
    runs-on: ubuntu-latest
    needs: docs
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          # Keep track of pyro-api master branch
          pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip
          pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          sudo apt-get install ninja-build
          pip install .[test]
          pip install coveralls
          pip freeze
      - name: Run examples
        run: |
          CI=1 pytest -vs --cov=pyro --cov-config .coveragerc --stage test_examples --durations 10
          grep -l smoke_test tutorial/source/*.ipynb | xargs grep -L 'smoke_test = False' \
                            | CI=1 xargs pytest -vx --nbval-lax --current-env
      - name: Submit to coveralls
        run: GITHUB_SHA="$GITHUB_RUN_ID" GITHUB_REF="" coveralls
  integration_1:
    runs-on: ubuntu-latest
    needs: docs
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          # Keep track of pyro-api master branch
          pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip
          pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          sudo apt-get install ninja-build
          pip install .[test]
          pip install coveralls
          pip freeze
      - name: Run integration test (batch 1)
        run: |
          pytest -vs --cov=pyro --cov-config .coveragerc --stage integration_batch_1 --durations 10
      - name: Submit to coveralls
        run: GITHUB_SHA="$GITHUB_RUN_ID" GITHUB_REF="" coveralls
  integration_2:
    runs-on: ubuntu-latest
    needs: docs
    strategy:
      matrix:
        python-version: [3.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U pip
          # Keep track of pyro-api master branch
          pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip
          pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          sudo apt-get install ninja-build
          pip install .[test]
          pip install coveralls
          pip freeze
      - name: Run integration test (batch 2)
        run: |
          pytest -vs --cov=pyro --cov-config .coveragerc --stage integration_batch_2 --durations 10
      - name: Submit to coveralls
        run: GITHUB_SHA="$GITHUB_RUN_ID" GITHUB_REF="" coveralls
  finish:
    needs: [unit, examples, integration_1, integration_2]
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
